### PR TITLE
Made it possible to load multipe JSON files

### PR DESCRIPTION
**Pull request by myeong**
I made some tweaks in the code, so that multiple JSON files can be loaded all together. 
Because Slack exports JSON files by date (one JSON file per day), so importing JSON file one by one is very burdensome. This change will make it easy to migrate multiple JSON files at once.

### CODE REVIEW

**Review by thomasloupe — COMMENTED** [review]
How are these sorted? By date? By order chosen?

**Comment by myeong** [comment]
the files are sorted by order chosen but Slack spits out by dates, so the files are sorted by date by default. Do you want me to explicitly sort the file names by dates?

**Comment by thomasloupe** [comment]
That's a good question. I guess I'm more concerned if folks rename their files, or don't, it's difficult for them to know when they import, how they'll export. I'm looking for ways for this to be a bit more obvious to the user the order in which files will be exported from Slackord into Discord.

**Comment by thomasloupe** [comment]
For now, I think this is a good default. Accepted, but I would like to see ways to improve clarity to the user if possible.

**Comment by myeong** [comment]
Thanks -- I will make some changes this week or so -- it's always to be safer and explicit. But if users use the input JSON files as they are from Slack, I think there will be no issues (the dates in the name of the JSON files are all messages' dates, not the import/export dates).

**Comment by richfromm** [comment]
@myeong , fwiw, I'm working on a hard fork (see https://github.com/richfromm/slack2discord), and supporting all of the json files from a single channel, as well as multiple channels, is on my near term plans.

**Comment by richfromm** [comment]
Fwiw, in my fork, all of the files from a single channel (parsed in date order) are supported as of https://github.com/richfromm/slack2discord/pull/8 (plan is to merge tomorrow)

Multiple channels is the next step.

**Comment by thomasloupe** [comment]
@richfromm, we can merge that whenever ready.

**Comment by richfromm** [comment]
@thomasloupe , I'm a bit confused. I thought we both agreed (see https://github.com/thomasloupe/Slackord/issues/8, which I just closed) that it would be best for me to work on a hard fork.

At this point it would be difficult to merge my work upstream, and I wrote it with the idea that that was not a requirement. I'm also not sure how the multiple channels case can even be done with the bot command approach. Your trigger is typing a command into a channel, which then (sort of) pulls the parsed messages into the channel. If the trigger is for a single channel, how does that direct messages to multiple channels? Mine works (sort of) the other way around. There is no bot command, just a discord client that searches the available channels for a matching name for each channel that is a dest, then uses that channel object to post the messages.

You are welcome to try to copy any of my code if you want, but maybe it would be simpler to just point anyone who wants to make changes to the Python version to my fork, and to put your energies into maintaining the Slackord2 .NET version. But ultimately it's up to you.

**Comment by thomasloupe** [comment]
This is mostly so you can contribute to closing issues or addressing requests which fit your fork's code. 

You don't need to commit anything to the repo or do anything at all with it if you don't wish to.

**Comment by richfromm** [comment]
Or, sounds fine. Feel free to point people with issues or requests to me, or even better if you'd be willing to update the README to point to my fork as one under (at least for now) active development

**Comment by thomasloupe** [comment]
Yep, will do that now.
Sorry I wasn't clear and just sent the collab invite out, that's on me! 😄

**Comment by thomasloupe** [comment]
Done! Please see the new README.

**Pull request merged**
